### ISSUE TITLE
Server crash when right-clicking on Fluorescent Lights

### ISSUE THREAD

**Issue by Tarasteed** [hypherionmc/hldocs#1]
Hi !
I recently wanted to use your mod on my server with Another quality Modpack, I started by doing some tests to see how it worked in single player and everything went well.
But when I wanted to use the Fluorescent Lights on the server, as soon as I right click on it, the server crashes.

Here is the crash log:
[crash-2022-01-16_17.31.36-server.txt](https://github.com/hypherionmc/hldocs/files/7877394/crash-2022-01-16_17.31.36-server.txt)

Please keep me informed! ;)

**Comment by hypherionmc** [comment]
Hey.

This is actually the wrong place to report bugs, but it's fine, I'll allow it :)

Looking at the crash report and code, it's just another case of me being a moron. I'll have to push out a fix for this

**Comment by Tarasteed** [comment]
Glad for the quick response!

Where should I have reported this problem in this case?
Should I tell the developers of Another Quality Modpack so they can do a hotfix when it's good?

**Comment by hypherionmc** [comment]
In the future you can report it here: https://github.com/Exploding-Creeper/Hyper-Lighting/issues

It might be good to let them know as well, just in case someone else runs into the same problem. I should release it by tomorrow

**Comment by Tarasteed** [comment]
Ok thanks you.

In that case, I will warn them directly on the discord just in case.

**Comment by hypherionmc** [comment]
Fix has been released, just pending Curseforge Approval. Sorry it took so long, but it's been a really busy week
